### ISSUE TITLE
Adding Appium to the list of Drivers

### ISSUE THREAD

**Issue by lfarnell** [rosolko/WebDriverManager.Net#1]
I've forked the project in order to add Appium to the set of drivers available. The project is hosted on bitbucket just like the phantomjs driver. The only difference is that the file name is like AppiumForWindows_1_4_16_1.zip instead of phantomjs-1.1.1.zip and i'm using the same code from the phantomjs driver with little modification which is the url in the configuration and it always seems to fail. I've been able to modify the code to get it too download the first image but never the latest version.

``` csharp

 WebDriverManagerConfig config = new WebDriverManagerConfig
        {
            binary = "Appium.exe",
            url = "https://bitbucket.org/appium/appium.app/downloads/AppiumForWindows_<version>.zip",
            pathVariable = "Appium.binary.path",
            architecture = Architecture.x32.ToString().Replace("x", "")
        };

        public string GetLatestVersion()
        {
            try
            {
                using (WebClient client = new WebClient())
                {
                   string version = null;
                    var doc = new HtmlDocument();
                    var htmlCode = client.DownloadString("https://bitbucket.org/appium/appium.app/downloads");
                    doc.LoadHtml(htmlCode);
                    var itemList = doc.DocumentNode.SelectNodes("//tr[@class='iterable-item']/td[@class='name']/a").Select(p => p.InnerText).ToList();
                    version = itemList.FirstOrDefault().Split('_')[1];
                    if (version != null || version != string.Empty)
                        Log?.Info($"Latest appium driver version is '{version}'");
                    else
                        Log?.Warn($"Problem with getting latest appium driver version. Parsed version is '{version}'");
                    return version;
                }
            }
            catch (Exception ex)
            {
                Log?.Error(ex, "Error occurred during getting last appium driver version");
                throw new WebDriverManagerException("Error occurred during getting last appium driver version", ex);
            }
        }
```

Any help would be appreciated.

**Comment by rosolko** [comment]
@lfarnell It's seems like application need to be installed after downloading. Not only downloading and unzipping, is it?

**Comment by rosolko** [comment]
@lfarnell 
Checkout new version and give some feedback.
Note: due to installation limitation - if project isn't start as admin - program will promt you for privilegies when install appium driver in system.

**Comment by lfarnell** [comment]
I will pull the changes when i get a chance this weekend. Thanks for beating me to the punch!

**Comment by rosolko** [comment]
@lfarnell
I've already implement and release this feature.
Just checkout new (1.1.1) and give some feedback.
If application required some changes.
Thanks.
