### ISSUE TITLE
FirefoxConfig

### ISSUE THREAD

**Issue by IljaSnakeware** [rosolko/WebDriverManager.Net#10]
`https://github.com/mozilla/geckodriver/releases/download/v<version>/geckodriver-v<version>-win64.zip`

Latest version is v0.19.1

`https://github.com/mozilla/geckodriver/releases/download/vv0.19.1/geckodriver-vv0.19.1-win64.zip`
^This will not work

**Comment by rosolko** [comment]
Fixed in 2.2.5
