### ISSUE TITLE
browser version detection on Linux MacOS

### ISSUE THREAD

**Issue by maksimetsa** [rosolko/WebDriverManager.Net#104]
useful to configure testing setup in Github Actions Environment on Linux machine

**Comment by alenmeister** [comment]
Are you saying this library does not work for you on all platforms?
Have you even read through the code?

**Comment by Ma3yTa** [comment]
Yes. I read. Dependent on Windows Registry @alenmeister

**Comment by alenmeister** [comment]
That's only if you're using the "matching_installed" value, afaik.

**Comment by Ma3yTa** [comment]
@alenmeister this is what I exactly need to match the version of google chrome installed on Github Actions environment

**Comment by alenmeister** [comment]
Ahh, well in that case I would update the feature request to state what you just said.
I agree, we should probably implement the same feature for MacOS and Linux sometime.

**Comment by Ma3yTa** [comment]
Github Environment description:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

Ubuntu 20.04
![](https://i.imgur.com/v7xjOM6.png)
MacOS
![](https://i.imgur.com/wFz1PSs.png)

**Comment by iouym** [comment]
@maksimetsa is this a feature you're still interested in? I've got something in mind that would address this.

**Comment by maksimetsa** [comment]
@iouym not interested anymore but can be useful for somebody else.

**Comment by iouym** [comment]
@rosolko this one can be closed off now merged as part of #133
