### ISSUE TITLE
this is a small library, but it copies nearly 120 other dlls to the release directory?

### ISSUE THREAD

**Issue by unominhtuan** [rosolko/WebDriverManager.Net#105]
this is a small library, but it copies nearly 120 other dlls to the release directory?

**Comment by rosolko** [comment]
This library depends only on 3 libraries:
1. AngleSharp
2. Microsoft.Win32.Registry
3. SharpZipLib

What exactly is the question?

**Comment by unominhtuan** [comment]
Sorry for the question missing information. when used with .net framework on windows. the library automatically copies nearly 200 other dll files ...
including netstandard, all files in system, System.AppContext ... and much more ...
I want to ask is there a solution for this?
![Image 1](https://user-images.githubusercontent.com/43975116/97125269-fedd8c00-1765-11eb-89eb-7b32c81f7f06.png)

**Comment by rosolko** [comment]
Just to confirm - is this behavior relate only for a single library dependency?

**Comment by rosolko** [comment]
@unominhtuan Can't reproduce. I've create a new clean project (.net 4.7.2), add a library and it add only necessary small set of libraries.
![image](https://user-images.githubusercontent.com/11458319/97211741-8cee5c80-17d0-11eb-8fd1-d1c10dd2ce8b.png)
