### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by benalewis** [rosolko/WebDriverManager.Net#106]
Doesn't work, create a new app with newest versions following instructions 

Install-Package WebDriverManager
Install-Package Selenium.WebDriver

Run test, failure.

**Comment by rosolko** [comment]
@brondavies What about stack-trace of error? Some information about configuration? Sample of code?

**Comment by brondavies** [comment]
> @brondavies What about stack-trace of error? Some information about configuration? Sample of code?

I think you mean @benalewis

**Comment by rosolko** [comment]
@brondavies Oops, yes, you're right. Sorry about that.
