### ISSUE TITLE
Won't install the correct version

### ISSUE THREAD

**Issue by FlafyDev** [rosolko/WebDriverManager.Net#109]
The library installs the Chromedriver for version 87 even though the Chrome installed on my computer is version 86.
Also, reinstalling Chrome doesn't seem to update to version 87 yet.

Because of the mismatching versions, Chrome crashes instantly.

**Comment by rosolko** [comment]
By default library get binary version from [url](https://chromedriver.storage.googleapis.com/LATEST_RELEASE).
And there chrome team set it to `87.0.4280.20` version.
If you want to get binary based on chrome version use `matching browser` strategy: `new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);`
