### ISSUE TITLE
New Edge - getting OpenQA.Selenium.WebDriverException: Unexpected error. Unknown error

### ISSUE THREAD

**Issue by iPiyushPatel** [rosolko/WebDriverManager.Net#111]
Hi team,
I'm getting the below error while trying to launch Edge browser the same way I did for Chrome. Please note - it works when we directly give Edge bin info via the path. 

**Error:**
`Message: 
    Initialization method AgilityHealth_Automation.Tests.AgilityHealth.Company.CompanyDashboardAddCompanyPage1Tests1.Setup threw exception. OpenQA.Selenium.WebDriverException: Unexpected error. Unknown error.
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
    RemoteWebDriver.ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
    EdgeDriver.ctor(EdgeOptions options)
    EdgeDriver.ctor()
    Browser.SetUp(TestEnvironment testEnvironment) line 64
    BaseTest.Setup() line 109`

**Code:**
Try 1:
` new DriverManager().SetUpDriver(new EdgeConfig(), "87.0.664.47", Architecture.X64);`

Try 2:
` new DriverManager().SetUpDriver(new EdgeConfig(), "87.0.664.47");`  //Same version my local edge version, I also confirmed from Edge Driver official site  - https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads

Try 3:
` new DriverManager().SetUpDriver(new EdgeConfig());`

Try 4:
`new DriverManager().SetUpDriver(new EdgeConfig(), VersionResolveStrategy.MatchingBrowser);`

**Video:**
https://drive.google.com/file/d/1awhaQBXgAwbGI0GRX4xTWSC5uC-caOuR/view?usp=sharing

Please suggest if I'm missing anything here.

**Comment by iPiyushPatel** [comment]
Well, I figured out the problem here. If I go to downloaded lib (at bin\Debug\Edge\87.0.664.52\X64) and change driver name to "MicrosoftWebDriver" then it works. Like this :
![image](https://user-images.githubusercontent.com/5212585/100708562-8c9a4000-33d2-11eb-9133-719fe0fd2c66.png)

Can you please fix this?

**Comment by rosolko** [comment]
`MicrosoftWebDriver` is a name of legacy edge browser. For a latest one they using `msedge` name.
But if you want to work with `MicrosoftWebDriver` better use `LegacyEdgeConfig` config.

**Comment by iPiyushPatel** [comment]
Hi @rosolko 
Well, I'm launching a new edge only. And I would like to use that only. Can you see my code above and also snaps? so this issue with the new Edge only unless I'm missing any configuration here. 

Please advice.

Thanks,

**Comment by rosolko** [comment]
If new edge require old name of driver you should definitely report this issue to Microsoft team. As for now, you can temporary override config and set proper name. Toy can find it in documentation -
[manual way](https://github.com/rosolko/WebDriverManager.Net#manual-way) or [custom implementation](https://github.com/rosolko/WebDriverManager.Net#if-you-want-use-your-own-implementation-you-need-to-create-driver-config-and-use-it-for-set-upex-get-setup-and-work-with-phantomjs-driver-from-taobao-mirror)

**Comment by iPiyushPatel** [comment]
Sure, got it, thanks much !  will give it a shot @rosolko !

**Comment by iPiyushPatel** [comment]
Hi @rosolko 
I've tried to use a custom config with just binary name change and it's not working. Actually, it no longer downloads binary (though it creates folders correctly), any idea?


`public class EdgeCustomConfig : EdgeConfig
    {
        public override string GetBinaryName()
        {
            return "MicrosoftWebDriver.exe";
        }
    }
}` 

and 

`new DriverManager().SetUpDriver(new EdgeCustomConfig(), BaseTest.TestEnvironment.EdgeVersion);`

Can you please help?
Thanks !

**Comment by rosolko** [comment]
Can you try to not specify version, just `new DriverManager().SetUpDriver(new EdgeCustomConfig());`?

**Comment by iPiyushPatel** [comment]
Hi @rosolko 
I've tried that and I'm getting the same error. i.e. it creates a new folder for the latest version (89) but it doesn't have any.exe
Please advice.
Thanks,

**Comment by iPiyushPatel** [comment]
Hi @rosolko 
FYI - I was able to resolve this issue by upgrading to Selenium 4 and having the below code:
`new DriverManager().SetUpDriver(new EdgeConfig(), VersionResolveStrategy.MatchingBrowser);

                var options = new EdgeOptions {UseChromium = true};
                Driver = new EdgeDriver(options);`

**Comment by rosolko** [comment]
Cool. So, can we close this issue?

**Comment by iPiyushPatel** [comment]
Yes, Closing this, thanks for support.
