### ISSUE TITLE
API to get Chrome Driver download directory

### ISSUE THREAD

**Issue by conradc-motwa25** [rosolko/WebDriverManager.Net#114]
I am using new DriverManager().SetUpDriver(new ChromeConfig(), "MatchingBrowser"); 

Is there a way to query the chromedriver.exe download directory so that I use it to call ChromeDriverService.CreateDefaultService( ).

**Comment by rosolko** [comment]
`SetUpDriver` method return path to `chromedriver.exe`. If you need directory just get if from returned path.

**Comment by conradc-motwa25** [comment]
For some reason, SetupDriver returns void instead of string.

**Comment by conradc-motwa25** [comment]
my WebDriverManager nuget package version is v2.11.0

**Comment by rosolko** [comment]
Opps. Looks like I don't publish a new version with that fix. Try to deal with it today.

**Comment by conradc-motwa25** [comment]
Thanks.  Please let me know when you publish it.

**Comment by rosolko** [comment]
2.11.1 version is published. Will be available soon.

**Comment by conradc-motwa25** [comment]
Thanks
