### ISSUE TITLE
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 88 Current browser version is 87.0.4280.141

### ISSUE THREAD

**Issue by TriStarGod** [rosolko/WebDriverManager.Net#117]
Hi guys,
I've been searching for an auto updating ChromeDriver library to run on my web scrapper server. After my recent implementation of this module, I thought all was well.

```
            new DriverManager().SetUpDriver(new ChromeConfig());
            var service = ChromeDriverService.CreateDefaultService();
            var options = new ChromeOptions();
```

Today, the app failed due to getting the latest `ChromeDriver `version (88) while the current Google Chrome was version (87) (The opposite of what I commonly face with this app). I resolved it by updating Google Chrome to 88.

Unfortunately, I did not have the time to debug it. Otherwise I would have checked the registry to see what version it was specifying. Instead, I wanted to know if its possible to force update Google Chrome to the latest version using Command line. Thanks!

**Comment by TriStarGod** [comment]
Resolved it with the following

`new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);`

**Comment by YoussofKhawaja** [comment]
new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser); 

this just don't work 

always get error System.Net.WebException: 'The remote server returned an error: (404) Not Found.' not sure but i think error is there no all version of chromedriver same as chrome version
