### ISSUE TITLE
Webdriver manager not support for . net 4.0

### ISSUE THREAD

**Issue by sidharathjain2** [rosolko/WebDriverManager.Net#119]
I m using this with .net 4.0 but it gives error

PM> Install-Package WebDriverManager
Installing 'WebDriverManager 2.11.1'.
Successfully installed 'WebDriverManager 2.11.1'.
Adding 'WebDriverManager 2.11.1' to Adinath.
Uninstalling 'WebDriverManager 2.11.1'.
Successfully uninstalled 'WebDriverManager 2.11.1'.
Install failed. Rolling back...
Install-Package : Could not install package 'WebDriverManager 2.11.1'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, 
contact the package author.

**Comment by rosolko** [comment]
It shouldn't. All of because target is `netstandard2.0` with `.NET Framework 4.6.1` equivalent.
