### ISSUE TITLE
Access to nonexistent path?

### ISSUE THREAD

**Issue by jamesaslett1985** [rosolko/WebDriverManager.Net#12]
When I try to use WebDriverManager as follows:

    public static void Initialize()

        {
            new DriverManager().SetUpDriver(new ChromeConfig());
            Instance = new ChromeDriver();
        }

I get this error message:

Message: System.UnauthorizedAccessException : Access to the path 'D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Chrome\2.36\X64' is denied.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

The Chrome folder does not exist. Is there a way around this?

**Comment by rosolko** [comment]
@jamesaslett1985 Run VS with administrator privileges.

**Comment by rosolko** [comment]
@jamesaslett1985 This happens because IDE located on system drive. Library trying to create folder and place binary there, but w/o access it isn't possible.

**Comment by rosolko** [comment]
Reopen if reproduce.

**Comment by jamesaslett1985** [comment]
This resolved the issue - many thanks
