### ISSUE TITLE
"new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);"

### ISSUE THREAD

**Issue by i7solar** [rosolko/WebDriverManager.Net#127]
"new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);"

Shoots an exception: System.Net.WebException: 'The remote server returned an error: (404) Not Found.'.

**Comment by YoussofKhawaja** [comment]
same here
