### ISSUE TITLE
IWebProxy setup is not working.

### ISSUE THREAD

**Issue by elumalaik** [rosolko/WebDriverManager.Net#129]
I am always getting 407 Proxy Authentication required message. Can you guide me any documentation to address this.

**Comment by rosolko** [comment]
https://github.com/rosolko/WebDriverManager.Net#using-with-proxy

**Comment by elumalaik** [comment]
Hi, Thanks for pointing out the URL. Can you please check if you can help on this.


  private class WebProxyStub : IWebProxy
        {
            public Uri RequestedUri { get; private set; }
            public ICredentials Credentials { get; set; }
            public Uri GetProxy(Uri destination) => new Uri("http://mycompanyurl");

            public bool IsBypassed(Uri host)
            {
                RequestedUri = host;
                return true;
            }
        }

 var webProxyStub = new WebProxyStub();
webProxyStub.Credentials = CredentialsCache.DefaultNetworkCredentials;

new DriverManager().WithProxy(webProxyStub).SetUpDriver(new ChromeConfig());


I used the above code for the proxy set up. It is still throwing error 407 - Proxy Authentication required.

**Comment by rosolko** [comment]
@elumalaik Unfortunately I have no ideas :(

**Comment by wakoye** [comment]
> @elumalaik Unfortunately for now I have no ideas :(

From what i see, the proxy instance is never assign to the WebRequest.
            WebRequest.DefaultWebProxy = proxy;

I have a new error after assigning it.
I will try to make it work
