### ISSUE TITLE
Does WebDriverManager.Net support sort of DesiredCapabilities

### ISSUE THREAD

**Issue by QA-automation-engineer** [rosolko/WebDriverManager.Net#131]
Hi everyone!

Actually, we are interested in `WebDriverManager.Net` for our project, but we can't find whether it supports `DesiredCapabilities` or not.

Please clarify this possibility.
Also some sort of example will be appreciated.
Thanks in advance.

**Comment by rosolko** [comment]
This library only download driver binaries such a `chromedriver.exe`.
`DesiredCapabilities` is related to `WebDriver` with comes from `selenium`.

**Comment by QA-automation-engineer** [comment]
thanks a lot
