### ISSUE TITLE
System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 90

### ISSUE THREAD

**Issue by jonathanlive** [rosolko/WebDriverManager.Net#136]
Please update the webdriver manager to get the new releases of ChromeDriver

Project:
C#
MsTest
Specflow
netcoreapp5.0

Chrome Version:  92.0.4515.107

**Comment by rosolko** [comment]
Library took version from created by chromedriver development team that you can find by the link https://chromedriver.storage.googleapis.com/LATEST_RELEASE

**Comment by jonathanlive** [comment]
I handled the issue using the manual implementation.

    new DriverManager().SetUpDriver(
                "https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_win32.zip",
                Path.Combine(Directory.GetCurrentDirectory(), "chromedriver.exe"),
                "chromedriver.exe"
            );

**Comment by rosolko** [comment]
This case you prefer manual way for version configuration and you should update it on each release. But latest version strategy update it automatically based on previously posted file
