### ISSUE TITLE
Latest Chrome release is beta

### ISSUE THREAD

**Issue by Salman0250** [rosolko/WebDriverManager.Net#137]
WebDriverManger is failing:  
System.InvalidOperationException: 'session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 92.0.4515.107 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe (SessionNotCreated)'

The https://chromedriver.storage.googleapis.com/LATEST_RELEASE URL currently returns 93.0.4577.15 but that's actually the beta version of Chrome, the currently latest released version is 92.0.4515.107. ChromeDriver bug? as https://chromedriver.chromium.org/downloads/version-selection says

In addition, the version of ChromeDriver for the current stable release of Chrome can be found at https://chromedriver.storage.googleapis.com/LATEST_RELEASE. However, using on this file may be less reliable than methods described above.

**Comment by rosolko** [comment]
Yes, look like this bug is going from chromedriver team.
