### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by jabracadabrah** [rosolko/WebDriverManager.Net#138]
We use .NET 5

When running this on an Ubuntu agent
`new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);`

This exception is thrown
```
  Error Message:
   System.TypeInitializationException : The type initializer for 'Microsoft.Win32.Registry' threw an exception.
  ----> System.PlatformNotSupportedException : Registry is not supported on this platform.
```

Will there be any Linux support?

**Comment by rosolko** [comment]
> Will there be any Linux support?

I have no dedicated plans for it, but feel free to contribute and create pull request with such feature

**Comment by ts46236** [comment]
Linux works, you just have to install chrome first. I was getting that error before I did that
