### ISSUE TITLE
Web drivers aren't being installed if pointed to an existing directory

### ISSUE THREAD

**Issue by n-ski** [rosolko/WebDriverManager.Net#155]
I have this test which installs drivers for Chrome and Firefox to the same directory (I use the current directory for simplicity).

```csharp
using NUnit.Framework;
using System;
using System.IO;
using WebDriverManager;
using WebDriverManager.DriverConfigs;
using WebDriverManager.DriverConfigs.Impl;

namespace SeleniumDriverTest
{
    public class ManagerTests
    {
        [Test]
        [TestCase(typeof(ChromeConfig))]
        [TestCase(typeof(FirefoxConfig))]
        public void Install_Success(Type configType)
        {
            IDriverConfig config = (IDriverConfig)Activator.CreateInstance(configType);

            string url = config.GetUrl64().Replace("<version>", config.GetLatestVersion());
            string binaryPath = Path.Combine(Environment.CurrentDirectory, config.GetBinaryName());

            DriverManager mgr = new();
            mgr.SetUpDriver(url, binaryPath);

            FileAssert.Exists(binaryPath);
        }
    }
}
```

`FileAssert.Exists` fails due to the invalid check in `SetUpDriver` which causes the method to return early even though no driver might be installed:
https://github.com/rosolko/WebDriverManager.Net/blob/b9120b5e6f7085aacc096bb03ffb18987617bcda/WebDriverManager/Services/Impl/BinaryService.cs#L23-L32

**Comment by rosolko** [comment]
Hi, thanks for reporting this issue out. Feel free to prepare pull request, it make final  fix faster!

**Comment by n-ski** [comment]
> Feel free to prepare pull request

Well it probably has to wait until this weekend but I'll see if I can fix this earlier.
