### ISSUE TITLE
DriverServiceNotFoundException - EdgeDriver - v2.12.2

### ISSUE THREAD

**Issue by igorrecioh** [rosolko/WebDriverManager.Net#156]
Hi all,

I am using WebDriverManager.Net with version 2.12.2 and when I try to run test with Edge Driver it throws this exception:

`OpenQA.Selenium.DriverServiceNotFoundException : The MicrosoftWebDriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://go.microsoft.com/fwlink/?LinkId=619687.`

The driver is correctly downloaded but not renamed automatically. I can solve this just renaming manually the driver...

I think this issue is similar to #98. I thought it was solved.

Thanks a lot!

**Comment by rosolko** [comment]
Not able to reproduce this issue, if have some additional info feel free to reopen this issue and put it into
