### ISSUE TITLE
Error FireFox

### ISSUE THREAD

**Issue by IljaSnakeware** [rosolko/WebDriverManager.Net#16]
Message: System.InvalidOperationException : Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line (SessionNotCreated)

**Comment by rosolko** [comment]
@IljaSnakeware Can you please show the code.
Based on message - looks like you have no firefox or install it in custom location and don't pass it in desired capabilities during session initialization.

**Comment by IljaSnakeware** [comment]
It worked fine but when I changed Firefox to __Firefox (in the folder), it installed a new one I think. The difference between them is: the working one has two folders in it (0.20.1 & 0.21.0), and the one that isn't working has only one (0.21.0)

**Comment by IljaSnakeware** [comment]
What do you mean? 
I'm working with Selenium.

**Comment by rosolko** [comment]
@IljaSnakeware I'm talking about original exception. It can be not from driver manager itself - issue can be on selenium side

**Comment by rosolko** [comment]
@IljaSnakeware Just show you code and exception with stacktrace

**Comment by IljaSnakeware** [comment]
But Chrome works fine

**Comment by IljaSnakeware** [comment]
StackTrace:	
RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
FirefoxDriver..ctor(FirefoxOptions options)
WebDriverFactory.CreateBrowserDriver(WebDriverType webDriverType)
WebDriverFactory.Create(WebDriverType webDriverType)
BrowserTests.InitializeDriver()

**Comment by IljaSnakeware** [comment]
Oops wrong button..

**Comment by Devqon** [comment]
I too have this issue, are there some custom flags to be set? I expected just like with the `ChromeDriver` it would pick up the driver automatically after running the `new DriverManager().SetUpDriver(new FirefoxConfig());`

This is the driver init:

```csharp
    private IWebDriver CreateFirefoxDriver()
    {
        new DriverManager().SetUpDriver(new FirefoxConfig());
        var driver = new FirefoxDriver();

        var options = new FirefoxOptions();
        if (_sessionSettings.Headless)
        {
            options.AddArgument("--headless");
        }
        options.AddArgument("--width=1920");
        options.AddArgument("--height=1080");

        return driver;
    }
```

It does get installed in the `bin` directory:

![image](https://user-images.githubusercontent.com/9316480/185555525-f96c67a2-99d9-4a7d-8826-a37df79e5cd6.png)

But I get this exception:

![image](https://user-images.githubusercontent.com/9316480/185555607-d8010119-db1f-489c-8935-a804ec602566.png)
