### ISSUE TITLE
WebDriverManager is not working

### ISSUE THREAD

**Issue by svadivel0006** [rosolko/WebDriverManager.Net#165]
Description of the problem: In Selenium C#, WebDriverManager is not downloading the old browser version drivers.

Browser and version: Chrome and V 86.0.4240.75

Operating system: Windows 10

WebDriverManager version: V 2.12.3

WebDriverManager call:
new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig());

WebDriverManager traces:

Message:
System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 86.0.4240.75 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

Error log:
Stack Trace:
WebDriver.UnpackAndThrowOnError(Response errorResponse)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeOptions options)
ChromeDriver.ctor()

Error Message:
![Error Message](https://user-images.githubusercontent.com/85741928/151982980-fb015c4e-9aaa-446c-8ab9-221be90b7935.png)

Chrome Installed Version:
![Chrome Installed Version](https://user-images.githubusercontent.com/85741928/151983130-efbc3ff8-c427-4c44-a8a2-81e9a717d25b.png)

Chrome Driver not found:
![Chrome Driver not found](https://user-images.githubusercontent.com/85741928/151983223-e7e99d53-1100-4991-bc74-06ba393d4f0c.png)

**Comment by jgelon** [comment]
Did you try to setup the Driver Resolve Strategy?
`new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);`

**Comment by svadivel0006** [comment]
Hi,

If the "Browser and version i.e. Chrome and V 86.0.4240.75" are installed in the system and the WebDrivermanager is downloading the "chromedriver" version i.e. "103.0.5060.53".

Please: If the drivers are successuflly download previously the "VersionResolveStrategy.MatchingBrowser", will work.

There are cases where the previous version of browsers have to used or run in VM or other machines for the first time and it is not working.

Regards,
Vadivel Sekar
