### ISSUE TITLE
Default download directory

### ISSUE THREAD

**Issue by Pookalton** [rosolko/WebDriverManager.Net#167]
How do I set or get the download directory?
It looks like it's thrown off the main program directory which might be an issue if the user doesn't have permission.
-Pook

**Comment by sarangsmk** [comment]
Hello, Need an option or argument which specifies **where actually the driver or root driver folder should be placed** (or do we have that option..?). If our code/software follows a structured hierarchy then this can cause issues as a new unexpected folder is being added.

**Comment by rosolko** [comment]
Released with 2.14.0 version
