### ISSUE TITLE
My chrome browser in machine is Version 98.0.4758.102 (Official Build) (64-bit) but chromedriver is installing 99 version and getting failed without able to s

### ISSUE THREAD

**Issue by YashwanthArulmozhi** [rosolko/WebDriverManager.Net#170]
My chrome browser in machine is Version 98.0.4758.102 (Official Build) (64-bit) but chromedriver is installing 99 version and getting failed without able to create session.

Chrome Version : 

![ChromeVersion](https://user-images.githubusercontent.com/26196470/156392668-bec85316-1e79-4ede-b7aa-d210f755cc88.png)

I use latest WEBDRIER MANAGER Version : 2.12.3 

Do we have to do anything from our end or is this a bug needs to be fixed? Not sure why it is picked advanced version which is not in my machine.

**Comment by rosolko** [comment]
All of because by default it took latest published by chrome team version. And not matching you local browser.

 `new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);`

**Comment by YashwanthArulmozhi** [comment]
Yes. I was able to figure the issue and I did the same and it worked fine. Thank you so much :)

**Comment by naviln** [comment]
> All of because by default it took latest published by chrome team version. And not matching you local browser.
> 
> `new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);`

Thankyou!
