### ISSUE TITLE
Firefox error

### ISSUE THREAD

**Issue by IljaSnakeware** [rosolko/WebDriverManager.Net#18]
At `namespace WebDriverManager.DriverConfigs.Impl`

"https://github.com/mozilla/geckodriver/releases/download/v<version>/geckodriver-v<version>-win64.zip";
This doesn't work, because the version already has a **v**

**Comment by rosolko** [comment]
It works.
This **v** symbol is removed in in firefox config in line [43](https://github.com/rosolko/WebDriverManager.Net/blob/master/WebDriverManager/DriverConfigs/Impl/FirefoxConfig.cs#L43)
