### ISSUE TITLE
Selenium C# WebDriverManager, latest version: 2.13.0 is not working and throwing error

### ISSUE THREAD

**Issue by svadivel0006** [rosolko/WebDriverManager.Net#191]
### WebDriverManager latest Version: 2.13.0 is not working and throwing error

**Screenshot:**

_**Error Details:**_

![image](https://user-images.githubusercontent.com/85741928/172895752-83e62d55-8892-4598-b84c-af5cb9b344b1.png)

_**Version Details:**_

![image](https://user-images.githubusercontent.com/85741928/172896031-8617d8eb-0dd4-4849-a726-0e19a7a84406.png)

_**Browser .exe downloaded and available details:**_

![image](https://user-images.githubusercontent.com/85741928/172897855-7e7d5bdc-6019-4795-8bf6-d327e4b9ed71.png)

**Comment by rosolko** [comment]
`OpenQA.Selenium` error is not related to this library. Also you're point that browser driver is downloadad and located on file system. It looks like there is an arror in some part of your code.

**Comment by svadivel0006** [comment]
Hi,

Thanks for the update, if the Beta version of chrome is being used, then the below mentioned error message is displayed

Error Details:
![image](https://user-images.githubusercontent.com/85741928/172976450-8686d1be-00d1-4736-979f-bbf9d6f6822c.png)

Kindly confirm whether, the WebDriverManager supports only the stable version or Beta version too.

Please Note: In some test scenarios the beta version is also used for testing
