### ISSUE TITLE
[🐛 Bug]: WebDriverManager downloads inappropriate versions of drivers and test executions are failing 

### ISSUE THREAD

**Issue by svadivel0006** [rosolko/WebDriverManager.Net#194]
When old versions of Chrome/Edge/Firefox are installed and when the WebDriverManager is used/run, it downloads the latest version of chromedrive.exe or respective drivers and hence the test executions are failing

Screenshots:

Error Details:
![Error Details](https://user-images.githubusercontent.com/85741928/176228516-b5c85b2c-f78f-4926-9fe0-bd28a58a1caa.png)

Browser Installed Version:
![Browser Installed Version](https://user-images.githubusercontent.com/85741928/176228560-615b621d-86af-4d64-95bb-40686ad147d1.png)

WebDriverManager driver downloaded details:
![WebDriverManager driver downloaded details](https://user-images.githubusercontent.com/85741928/176228615-444250e7-9a07-4f33-a759-5b51dd23453c.png)

**Comment by rosolko** [comment]
Library download latest driver by default. For old browser version lock exact version or update it to latest one
