### ISSUE TITLE
[🐛 Bug]: WebDriverManager with the "MatchingBrowser" command displays error in Selenium C#

### ISSUE THREAD

**Issue by svadivel0006** [rosolko/WebDriverManager.Net#199]
### **_Screenshot:_**
![image](https://user-images.githubusercontent.com/85741928/179395256-df9f9192-ea7c-4993-8aba-1949889973c2.png)

**Comment by renatosc** [comment]
Try using:

`new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);`

and also make sure that there is no previous **"chromedriver.exe"** in the bin directory.

**Comment by series0** [comment]
I can't even get to that stage.

I'm current on Visual Studio and v4.0.30319 of WebDriverManager

this line of code:

new WebDriverManager.DriverManager().SetUpDriver(new WebDriverManager.DriverConfigs.Impl.ChromeConfig(), VersionResolveStratgey.MatchingBrowser);

is ... unusual.

The ChromeConfig other people use is not 'available' unless I decorate the name that way.  The VersionResolveStrategy is not available at all.  Where is that defined.  I can't even get to the 'Hey this doesn't work phase'

**Comment by rosolko** [comment]
@series0 Latest webdrivermanager has 2.16.2 version not  4.0.30319

**Comment by series0** [comment]
Well yes, now that I look again at the NuGet PM, I see it listed as 2.16.2 which was what I already had installed.

I was looking at the Runtime Version in the Properties window.

But where is VersionResolveStrategy defined?
Where is ChromeConfig() defined for that matter that it has to be thus decorated to compile?

**Comment by rosolko** [comment]
WebDriverManager.DriverConfigs.Impl

**Comment by series0** [comment]
OK, so found it in the Helpers section so final command does compile now.  Here it is:
new WebDriverManager.DriverManager().SetUpDriver(new WebDriverManager.DriverConfigs.Impl.ChromeConfig(), WebDriverManager.Helpers.VersionResolveStrategy.MatchingBrowser);

Runtime Exception generated was:
![image](https://user-images.githubusercontent.com/97316990/207677421-ce483589-717f-47be-a646-70dc65f20e63.png)

**Comment by brkacar** [comment]
No solution in this? I got the same error after chrome is updated. Tried MatchingBrowser didnt work either.

                
new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);
                driver = new ChromeDriver();


System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 111
Current browser version is 113.0.5672.64 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by PwccaCode** [comment]
i have the same issue, the main program seems to be that VersionResolveStrategy.MatchingBrowser tries to connect to google api for chrome and download based on your SO + chromeversion
but if that combination doesn't exist on the server it results in an error
