### ISSUE TITLE
Add Mac arm64 support

### ISSUE THREAD

**Issue by Parahet** [rosolko/WebDriverManager.Net#204]
Please add to [ChromeConfig.cs](https://github.com/rosolko/WebDriverManager.Net/blob/master/WebDriverManager/DriverConfigs/Impl/ChromeConfig.cs)
support for Mac arm64
here is solution:

```
private string GetUrl()
        {
#if NETSTANDARD
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                return $"{BaseVersionPatternUrl}chromedriver_mac64{(RuntimeInformation.ProcessArchitecture == Architecture.Arm64 ? "_m1" : "")}.zip";
            }

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                return $"{BaseVersionPatternUrl}chromedriver_linux64.zip";
            }
#endif

            return $"{BaseVersionPatternUrl}chromedriver_win32.zip";
        }

**Comment by Parahet** [comment]
I tested driver `105.0.5195.52/chromedriver_mac64_m1.zip` comparing to `105.0.5195.52/chromedriver_mac64.zip` (which is running on Intel)
One simple test execution time decreased from 144sec to 115sec ~ 20% difference

chip: Apple M1 Pro

**Comment by rosolko** [comment]
@Parahet Thanks! Released with 2.16.0 version. Support: Chrome, Edge, Firefox.

**Comment by Parahet** [comment]
awesome! thank you

**Comment by Parahet** [comment]
@rosolko As there was some changes in chromedriver versions, we don't have `mac64_m1` version anymore, currently its `mac_arm64`, we need to adjust 
```
return
    $"https://chromedriver.storage.googleapis.com/<version>/chromedriver_mac{(RuntimeInformation.ProcessArchitecture == Architecture.Arm64 ? "_arm64" : "")}.zip"
```
https://chromedriver.storage.googleapis.com/index.html?path=107.0.5304.62/
![image](https://user-images.githubusercontent.com/23723328/198262327-f91a310e-70bd-457f-a314-7e4155b008fe.png)
