### ISSUE TITLE
The example in readme.md is unreliable

### ISSUE THREAD

**Issue by ant-222** [rosolko/WebDriverManager.Net#209]
The usage example in `readme.md` does not work reliably because is depends on a temporal coupling between two invocations:

    new DriverManager().SetUpDriver(new ChromeConfig());
    _webDriver = new ChromeDriver();

In addition to the temporal couping and out-of-bandwidth signalling, this approach will not work if an old verison of `chromedriver.exe` is presenent in the program directory, because it will override the downloaded driver. By experiment I found that `SetUpDriver()` returns the full name of the downloaded driver executable, whereas the `ChromeDriver` constructor may accept not the full name, but the path to the driver location, which is an internal inconsistency in the *API* and forces the programmer to extract the directory path from the file path:

    string file       = new DriverManager().SetUpDriver(new ChromeConfig());
    string dir        = Path.GetDirectoryName( file ); // Redundant!
    IWebDriver driver = new ChromeDriver     ( dir  );

Can you please remove this inconsistency, document the return value of `SetUpDriver()`, and fix the example in `readme.md` accordingly?

**Comment by jbcrowley** [comment]
Thank you for entering this issue. I was running into the same problem and couldn't figure out where the mismatched driver was coming from. This code snippet fixed it.

**Comment by rosolko** [comment]
Work as designed
