### ISSUE TITLE
Invalid chromedriver download URL for Chrome 106+ on Mac M1

### ISSUE THREAD

**Issue by fmoliveira** [rosolko/WebDriverManager.Net#210]
Hi everyone! The download URL generated by the library no longer works for Chrome 106+ on Mac M1 because the filename suffix changed on the ChromeDriver repository at https://chromedriver.storage.googleapis.com/.

Previously, Mac M1 binaries were named like `chromedriver_mac64_m1.zip` and the latest two versions follow the pattern `chromedriver_mac_arm64.zip`. This affects users with Mac processors M1/M2 on versions 106.0.5249.61+ and 107+.

I have a working bandaid fix on my fork at https://github.com/fmoliveira/WebDriverManager.Net/commit/b57457ff56a5beb006b4962c04b692b0ad7456f9 , but this is not backwards compatible.

<details>
<summary>Any thoughts on this and ideas on how we could approach it? My initial brainstorming:</summary>

- How do we tell if this new suffix is reliable? Is there an accessible channel to discuss this with the maintainers of the chromedriver downloads? Hoping it would be possible to revert this breaking change, or at least understand its context and whether we can rely on it.
- How would we tell which suffix to pick for Mac M1 binaries? Is there a better way than hard-coding the version number that introduced this breaking change? Should WebDriverManager consider downloading the index to help resolve this, or is hard-coding when the change happened the best course of action to keep things simple?
- The method `ChromeConfig.GetUrl`, responsible for returning the URL pattern, is unaware of the version number, so right now it does not have the information needed to figure out which filename pattern to return. The `DriverManager.SetUpDriver` method has that information and could pass it down to `ChromeConfig.GetUrl`. Is this proposal a decent idea? Does anybody have a more elegant recommendation to address this?
</details>

<details>
<summary>Details about the broken link</summary>

Because of the current implementation of `ChromeConfig.GetUrl` that always appends the suffix `mac64_m1` ([see reference here](https://github.com/rosolko/WebDriverManager.Net/blob/2bfdfb085eb595062b272e1019b24ba660f09168/WebDriverManager/DriverConfigs/Impl/ChromeConfig.cs#L37-L41)), the latest versions coming out with the new suffix `mac_arm64` resolve to a broken link such as https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip. 
</details>

My environment:
- macOS Monterey 12.6 (ARM M1 processor)
- Chrome 106.0.5249.91
- .NET Core 6.0.401

Also, I would be happy to submit a PR after we discuss it and draft an idea on how to structure it properly for backwards compatibility.

Thanks in advance!

**Comment by fmoliveira** [comment]
Found the commit that introduced the new suffix: https://chromium.googlesource.com/chromium/src/+/82f7c15619cb1400875276b6cb1ea0db02d21026%5E%21/chrome/test/chromedriver/support/release/nest-pack

Change tracked at: https://chromium-review.googlesource.com/c/chromium/src/+/3925559

The suffix `_m1` was filed as a bug here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4215 
> "The existing naming is misleading for the owners of the laptops with m2 processor."

So this is it. I believe hard-coding the version number that introduced the new suffix is ok then?

**Comment by jmalczak** [comment]
Guys, is there any release ready with this fix?

**Comment by fmoliveira** [comment]
> Guys, is there any release ready with this fix?

Yes, version 2.16.1
