### ISSUE TITLE
Release to fix #214

### ISSUE THREAD

**Issue by FelixLeChat** [rosolko/WebDriverManager.Net#218]
Hi WebDriverManager team,

We are experiencing the bug fixed in the latest [fix: mac arm64 suffix](https://github.com/rosolko/WebDriverManager.Net/pull/214).

When are you planning to release a new version (2.16.1 or 2.17.0) for this fix ?

Thanks for the amazing lib!

**Comment by rosolko** [comment]
Update package published with 2.16.1 version
