### ISSUE TITLE
Product version of .dll does not update with e.g. netsparkle

### ISSUE THREAD

**Issue by StefanRvdB** [rosolko/WebDriverManager.Net#262]
It seems that if you've used the WebDriverManager previously and have the *.dll setup in a wixProject the version of the .dll does not update when using an update tool such as NetSparkle;

e.g. the version in my MSI is set to '34816 kb; modified date: 2023-08-09 18:44'

when I perform a clean install, the installed DLL equals the one from my MSI.

when I attempt to update an older installed version with this newer MSI through e.g. Netsparkle, the version of the DLL remains the same, resulting in an error such as:
Unexpected error while attempting to run or while running test: System.MissingMethodException: Method not found: 'Void WebDriverManager.DriverManager..ctor(System.String)'.

**Comment by n-ski** [comment]
I'm assuming this is related to assembly version always being the same (1.0.0.0), in which case this can be easily fixed by defining project version using `<Version>` property instead of `<PackageVersion>`.
