### ISSUE TITLE
Chrome on Linux gives "System.Exception : Unable to locate installed browser for runtime platform Unix"

### ISSUE THREAD

**Issue by sbonds** [rosolko/WebDriverManager.Net#273]
It turns out that WebDriverManager.Net has a very specific list of names that it searches for which does not include the name "chrome", which is the name of the binary in a ZIP downloaded from Google. One workaround is to symlink it from the name "google-chrome", but another fix is to also search for "chrome".

See code to do this in PR #272.

**Comment by rosolko** [comment]
Merged. Will be available as part of next release
