### ISSUE TITLE
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.   ----> System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 116 Current browser version is 118.0.5993.71 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)

### ISSUE THREAD

**Issue by aarif313** [rosolko/WebDriverManager.Net#284]
ChromeDriver is not able to support latest version of Chrome getting below exception

System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 116
Current browser version is 118.0.5993.71 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)

**Comment by aarif313** [comment]
Using latest versions of NuGet packages

Selenium WebDriver --> 4.14.1

WebDriverManager --> 2.17.1

**Comment by maevskiy-k-abcloudz** [comment]
I have the same error.

**Comment by PatrickMurrell** [comment]
The issue I found was that I was using a cached version of chromedriver in my project build debug folder. I had to close all active selenium instances, delete the driver exe, and re-run the program.

**Comment by rosolko** [comment]
Can't reproduce
