### ISSUE TITLE
ChromeWebdriverManager fails with Exception

### ISSUE THREAD

**Issue by SergeyPirogov** [rosolko/WebDriverManager.Net#3]
For ChromeWebdriverManager got exception at the very beginning:

Unhandled Exception: WebDriverManager.Helpers.WebDriverManagerException: Error occurred during browser driver archive downloading ---> System.Net.WebException: The remote server returned an error: (404) Not Found.

**Comment by rosolko** [comment]
@SergeyPirogov Can you please specify what sort of driver do you try to initialize?

**Comment by SergeyPirogov** [comment]
@rosolko Chrome

**Comment by rosolko** [comment]
@SergeyPirogov Fixed in version 1.2.3

**Comment by SergeyPirogov** [comment]
Unhandled Exception: OpenQA.Selenium.DriverServiceNotFoundException: The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.

**Comment by rosolko** [comment]
@SergeyPirogov Can you please checkout build 1.3.0 and verify this on your side?
