### ISSUE TITLE
can not download new chrome driver from today as there have changed directory chrome version 122

### ISSUE THREAD

**Issue by mraakashjoshi** [rosolko/WebDriverManager.Net#314]
Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_locationUnable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by garry-edmonds** [comment]
@mraakashjoshi 

I've just tried this without an issue.
My setup is Windows Chrome - Version 122.0.6261.58 (Official Build) (64-bit)
WebDriverManager - 2.17.2
Using .Net Framework 4.7.2
Driver is downloaded into the ..\bin\environment\Chrome\<version number>\x64 in my instance.

What configuration are you running and and can you share your Stacktrace error.
It may help someone to resolve this with you.

**Comment by rosolko** [comment]
@mraakashjoshi Correct me if I'm wrong - you're using a Selenium built-in manager to download new chrome driver? If yes, this issue is not related to current library

**Comment by mraakashjoshi** [comment]
i am using this setting and getting error also tried today.

new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);

My setup is Windows Chrome - Version 121.0.6167.185 (Official Build) (32-bit)
Using .Net Framework 4.6.2
WebDriverManager - 2.17.2

giving error as below.

Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_locationUnable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by mraakashjoshi** [comment]
It's my mistake. i found my issue.
