### ISSUE TITLE
Any way to automatically download latest Chrome (not chromedriver)?

### ISSUE THREAD

**Issue by FrenziedIM** [rosolko/WebDriverManager.Net#317]
If I don't open Chrome.exe, going to chrome://about and relaunch, my app doesn't work.

I want 100% uptime on my server, and therefore if there is a chrome update, I want everything to be applied automatically.

Right now, it's updated my chromedriver, but not my chrome, resulting in: This version of ChromeDriver only supports Chrome version 122

How can I update chrome automatically?

**Comment by rosolko** [comment]
Not related to library.
Look for something like this https://www.google.com/chrome/update/

**Comment by FrenziedIM** [comment]
"Chrome applies it automatically when you close and reopen the browser"
That's the issue.
You need to manually restart Chrome.
