### ISSUE TITLE
EdgeDriver get wrong version

### ISSUE THREAD

**Issue by gabstibu** [rosolko/WebDriverManager.Net#333]
Selenium manager get Edge version 129.0.2751.0.
stable version is 127.0.2651.86 
![Sem título](https://github.com/user-attachments/assets/fd93d664-798e-4a1b-8f33-300ddcee93b1)
![image](https://github.com/user-attachments/assets/6f1156fa-97cc-4f0b-bf70-d383566698c5)

**Comment by rosolko** [comment]
It get latest driver version marked by microsoft as stable
