### ISSUE TITLE
Setting up Edge driver works only if a version is mentioned

### ISSUE THREAD

**Issue by CNIstrate** [rosolko/WebDriverManager.Net#334]
Hi! 
I started having issues with Edge driver when setting it up. 

Failing code:
`                    new DriverManager().SetUpDriver(new EdgeConfig());
`
![image](https://github.com/user-attachments/assets/db8414fc-56a7-4e17-bc09-fd8ea1b61d91)

Working code:
![image](https://github.com/user-attachments/assets/1a282ed8-5f55-4758-94eb-085c30b94910)

Seems like edge is properly set up only if a version is mentioned.

Any ideas regarding this issue?

Thanks!

**Comment by CNIstrate** [comment]
As a current workaround, I am using this method to get the current Edge version installed on my windows machine and Azure Agents.

```
private static string GetEdgeVersion()
{
    var localMachine = @"HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}";
    var edgeVersion = Registry.GetValue(localMachine, "pv", null);
    return edgeVersion.ToString();
}
```

My Azure pipeline has a script which installs all browsers I need before running the tests to ensure I have latest version on them, so this way I can pass the latest version of the browser in the code based on what I have installed on my machine.

**Comment by rosolko** [comment]
Can't reproduce
