### ISSUE TITLE
Non-windows release date?

### ISSUE THREAD

**Issue by FrameBassman** [rosolko/WebDriverManager.Net#39]
You have several changes for non-windows environment after 2.4.0 release (https://github.com/rosolko/WebDriverManager.Net/commit/a1713e6178891a5e19bdbf05c47e4f59a3a3c011 or https://github.com/rosolko/WebDriverManager.Net/commit/b9781a2e07befab8369915c97084af3d13a371a6).
When you are going to release this changes?

**Comment by rosolko** [comment]
Tonight or tomorrow morning
