### ISSUE TITLE
FireFoxDriverManager exception

### ISSUE THREAD

**Issue by SergeyPirogov** [rosolko/WebDriverManager.Net#4]
Unhandled Exception: WebDriverManager.Helpers.WebDriverManagerException: Error occurred during adding(updating) browser driver environment variable ---> System.Security.SecurityException: Requested registry access is not allowed.

**Comment by rosolko** [comment]
@SergeyPirogov To work with system variables you need to administrator privileges.

**Comment by SergeyPirogov** [comment]
@rosolko Ok, how to enable them? I've just put my peace of code as you showed in example

**Comment by rosolko** [comment]
@SergeyPirogov Run you tests/IDE with admin administrator privileges.

**Comment by SergeyPirogov** [comment]
Unhandled Exception: OpenQA.Selenium.DriverServiceNotFoundException: The geckodriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/geckodriver/releases.

**Comment by rosolko** [comment]
@SergeyPirogov Good. This is okay. Check please path variables for `webdriver.gecko.driver`. If it existas and contains valid value add `%webdriver.gecko.driver%` to `PATH`. For now I didn't add it automatically because of issue #2

**Comment by SergeyPirogov** [comment]
@rosolko Well variable exists and have valid path, but still require me to set Variable. 

Of course, I can easily add it, but the main purpose of the library is to do that automatically, so I will be able to run my tests whenever I want.

**Comment by rosolko** [comment]
@SergeyPirogov I can enable `PATH` overriding by default, but as I sad previously the way to override them isn't so good :(

**Comment by SergeyPirogov** [comment]
@rosolko So while it's not solved people will not use this library. Because as a user i want to add library and see magic, but now I struggle will all this problems.

Moreover I think this behavior should be documented somehow

**Comment by rosolko** [comment]
@SergeyPirogov Can you please checkout build 1.3.0 and verify this on your side?

**Comment by SergeyPirogov** [comment]
Now it works well
