### ISSUE TITLE
GetLatestVersion for ChromeConfig hardcoded to ChromeDriver 74

### ISSUE THREAD

**Issue by pkell** [rosolko/WebDriverManager.Net#42]
In recent versions, the GetLatestVersion method in ChromeConfig is using the URL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_74".
This is fetching the latest release of V74 but ChromeDriver is already at V75. 
Should the URL not be "https://chromedriver.storage.googleapis.com/LATEST_RELEASE" ?

**Comment by rosolko** [comment]
Available in 2.5.1 version
