### ISSUE TITLE
System.ArgumentException: Illegal characters in path

### ISSUE THREAD

**Issue by Taylor-Daly** [rosolko/WebDriverManager.Net#44]
I'm getting the error System.ArgumentException: Illegal characters in path in the GetBinDestination method. I'm trying to use ChromeDriver with automatic setup.

https://github.com/rosolko/WebDriverManager.Net/blob/df1bc94b14be833d75f64b669426d32641f8e938/WebDriverManager/Helpers/FileHelper.cs#L21

**Comment by rosolko** [comment]
@Taylor-Daly Can't reproduce. On my side all going well

**Comment by Draclain** [comment]
Hello, I am writing to report I have the same exception generated but with firefox.
System.ArgumentException : Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String[] paths)
   at WebDriverManager.Helpers.FileHelper.GetBinDestination(String driverName, String version, Architecture architecture, String binName)
   at WebDriverManager.DriverManager.SetUpDriver(IDriverConfig config, String version, Architecture architecture)

I have running WebDriverManager 2.12.3 with Firefox browser 94.0.1 and the current latest version of mozilla/geckodriver is 0.30.0.

It appears the issue happen as the following method return this string as the version "\n  0.30.0\n \n".
DriverManager.GetVersionToDownload(config, version); 

The line feed escape sequences are apparently considered illegal in "Path.Combine". 

Everything runs smooth if I hardcode the version "0.30.0" in place of "Latest" in SetUpDriver method.

My tests were fined 2 days ago and stopped working suddenly without any changes, neither update of geckodriver. I currently try to find out what has changed.

**Comment by rosolko** [comment]
@Draclain Hi, just update to 2.12.4 version. Fix related issue https://github.com/rosolko/WebDriverManager.Net/issues/172
