### ISSUE TITLE
Cross-Platform .NET Core Support

### ISSUE THREAD

**Issue by gerryhernandez** [rosolko/WebDriverManager.Net#5]
I was about to write a similar package (inspired by the Java package of the same name, which it looks like you've taken a similar direction), but then I came across this project. Awesome!

So Selenium is on the brink of getting .NET Core support. There is an open pull request (https://github.com/SeleniumHQ/selenium/pull/2269) and a preview package is available on NuGet (https://www.nuget.org/packages/CoreCompat.Selenium.WebDriver/2.54.0-beta002). **I am proposing cross-platform (Windows, Mac OS, Linux) .NET Core support for WebDriverManager.NET**.

I'm still very new with .NET Core and I've only glanced at this code, but I believe the bulk of the necessary changes would be (in no particular order):

- Migrate to newer .NET Core project structure (project.json).
- `WebDriverManager.Services.Impl.VariableService` will need to implement platform-specific path manipulation for Linux and Mac; rename/refactor the existing Windows implementation.
- `WebDriverManager.DriverConfigs.IDriverConfig` implementations will need to be platform-agnostic. I would propose that the existing classes (`ChromeConfig`, `FirefoxConfig`, etc) should be responsible for detecting the runtime platform and transforming results as necessary. For example, the binary name on Mac/Linux would not end in ".exe", among other differences.
- Perhaps make a PlatformHelper/Service to aid with the previous bullet point?
- Probably more, but this is what I came up with on first glance.

Let me know what you think. I'd love to help out. Thanks!

**Comment by rosolko** [comment]
@gerryhernandez Looks interesting. But I'm also new with .NET Core. So I can't promise a quick solution. So **PR** are very welcome.
