### ISSUE TITLE
Can't run tests in parallel using WebDriverManager

### ISSUE THREAD

**Issue by NetanelMosheCohen** [rosolko/WebDriverManager.Net#56]
My project using Selenium + MSTest. Until now, I used the chromedriver from the nuget package and the tests are running perfectly in parallel. 
I tried to use WebDriverManager instead of the chromedriver nuget package - when I run 1 test, everything works correctly. But when I trying to run tests in parallel (even 2 tests), one of the tests fails immediately and the 2nd test continue and running OK. It seems that the first test using the chromedriver and then the 2nd test can't use it too, so it fails:

System.ComponentModel.Win32Exception: 'The process cannot access the file because it is being used by another process'

Am I missing something? does WebDriverManager supports parallel run?
You can see the code in the attachment.

Thanks 

![WhatsApp Image 2020-01-07 at 16 36 58](https://user-images.githubusercontent.com/56232437/71918552-305f7980-318b-11ea-960e-c0abcbc15822.jpeg)

**Comment by rosolko** [comment]
@NetanelMosheCohen Can you please paste a full stack trace of error. Since I've lock unzip operation this error looks quite strange.

**Comment by NetanelMosheCohen** [comment]
@rosolko There is no stack trace for this error. 
I wrapped these code lines with lock and it fixed the issue. 
But maybe you want to fix it on your side?

**Comment by rosolko** [comment]
But I already wrap unzip method with lock, this is the only one place when the binary is copy to target path

**Comment by NetanelMosheCohen** [comment]
yes but afterwards, at test run, the first test accessing the chromedriver and the second test that is running at the same time can't use it too. 
I don't know how it is implemented but this is the behavior. Did you test it with parallel run?   
@rosolko

**Comment by rosolko** [comment]
@NetanelMosheCohen Yes, you're right. Project test run in a parallel but not for same config and lack for such test

**Comment by NetanelMosheCohen** [comment]
@rosolko Sorry, I didn't understand what you wrote in the last comment, can you explain it again please?

**Comment by rosolko** [comment]
@NetanelMosheCohen Test inside this project. I don't create a test which execute setup method for single config. Will extend them and try to fix a problem

**Comment by rosolko** [comment]
Lock full `SetUpDriver` method not only unzip. Will be available with 2.8.0 version
