### ISSUE TITLE
Unable to add the nuget package in solution done in .net framework 4.7.2

### ISSUE THREAD

**Issue by lkkushan101** [rosolko/WebDriverManager.Net#57]
Hi,

I'm unable to add the nuget package for a solution done in .net framework 4.7.2. Please advice. 
Following is the error i'm getting 

Install-Package : Could not install package 'WebDriverManager 2.7.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:

**Comment by lkkushan101** [comment]
For now I'm using version 2.2.7 of webdriver manager as the framework is used on .NETFramework,Version=v4.7.2. Hope the latest 2.8.0 version resolves this issue.. Please reply soon

**Comment by rosolko** [comment]
@lkkushan101 Hi, sorry for a long delay. Unfortunately I don't know why can't it target NETFramework4.7.2, documentation says that netstandard2.0.
Unfortunately for now I don't know how to fix it.
If you have a solution, please share them.
Thanks!
