### ISSUE TITLE
Unable to use Firefox driver on Linux and Mac Os

### ISSUE THREAD

**Issue by alexeypato** [rosolko/WebDriverManager.Net#58]
Hi

With the current implementation, it’s not possible for us to run a Firefox driver on Linux and Mac Os machines.

In order for the correct driver to download, you need to update FirefoxConfig class as ChromeConfig for example and add a method for unzipping * .tar.gz archives to BinaryService class.

**Comment by rosolko** [comment]
Unfortunately for now I have almost no time to engage in the project, so PR are very welcome!

**Comment by rosolko** [comment]
@alexeypato Available in 2.9.0
