### ISSUE TITLE
New Microsoft Edge Browser doesn't work

### ISSUE THREAD

**Issue by Seploid** [rosolko/WebDriverManager.Net#59]
I tried to use your library to create driver for new Microsoft Edge browser and get following error:

: OpenQA.Selenium.DriverServiceNotFoundException : The MicrosoftWebDriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://go.microsoft.com/fwlink/?LinkId=619687.

My code is very simple:

            new DriverManager().SetUpDriver(new EdgeConfig());
            return new EdgeDriver();

I guess that main issue in name of the file - it should be msedgedriver.exe

Could you fix it?

**Comment by rosolko** [comment]
@Seploid This issue going from selenium. Inside library this driverr already have `msedgedriver` file name
