### ISSUE TITLE
Target Framework

### ISSUE THREAD

**Issue by svenruechel** [rosolko/WebDriverManager.Net#6]
Is it possilbe to set the target framework to 4.0 or 4.5? I don't want to force everybody using my application to download the latest framework.

**Comment by rosolko** [comment]
@svenruechel I set target framework to 4.5.2 and publish new version 2.2.1

**Comment by svenruechel** [comment]
Thank you!

Von: Alexander Rosolko [mailto:notifications@github.com]
Gesendet: Freitag, 28. April 2017 11:33
An: rosolko/WebDriverManager.Net <WebDriverManager.Net@noreply.github.com>
Cc: Sven Rüchel <sven.ruechel@souffleuse.de>; Mention <mention@noreply.github.com>
Betreff: Re: [rosolko/WebDriverManager.Net] Target Framework (#6)


@svenruechel<https://github.com/svenruechel> I set target framework to 4.5.2 and publish new version 2.2.1
