### ISSUE TITLE
Chromedriver launch failing after updating to v80

### ISSUE THREAD

**Issue by roysouma** [rosolko/WebDriverManager.Net#63]
As soon as Chrome updated automatically to v80 Webdriver manager is failing to launch instance. I reverted back to v79 and things started working fine again. But unfortunately due to company policy chrome automatically updates again to v80 and results in failure.

```
public IWebDriver GetDriver()
{
    new DriverManager().SetUpDriver(new ChromeConfig());
    _chromeDriverService = ChromeDriverService.CreateDefaultService();
    _chromeDriverService.HideCommandPromptWindow = true;
    ChromeOptions options = new ChromeOptions();
    options.AddArgument("--log-level=3");
    _webDriver = new OpenQA.Selenium.Chrome.ChromeDriver(_chromeDriverService, options);
    _webDriver.Manage().Window.Maximize();

    return _webDriver;
}
```

**Comment by rosolko** [comment]
Unable to reproduce this bug.
Reproduce your code in a test, run it and it's works well.

My chrome has version - 80.0.3987.87 (Official Build) (64-bit)
Library download chromedriver with version - 80.0.3987.16

Can you please provide double-check that issue and provide more info.
Browser verseion, downloaded driver version and test logs with error stack trace.

**Comment by roysouma** [comment]
Hi rosolko,

The error message is : Message = "session not created: This version of ChromeDriver only supports Chrome version 78 (SessionNotCreated)"

The stacktrace is as below:
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at ConsoleApp1.WebDriver.ChromeDriver.GetDriver() in C:\Users\roysouma\source\repos\TaxBotApp\ConsoleApp1\WebDriver\ChromeDriver.cs:line 102
   at Tax_Tool.UserControlFlex.Worker_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\roysouma\source\repos\TaxBotApp\ConsoleApp1\UserControlFlex.xaml.cs:line 109

My chrome version is 80.0.3987.16 and I checked the downloaded version is also correct in the path C:\Users\roysouma\source\repos\TaxBotApp\ConsoleApp1\bin\Debug\Chrome\80.0.3987.16\X64.

I'm also unable to figure out why this is happening as it is working fine with v79 an downloaded version is also fine as stated above.
Others  in my team are also the same problem.

**Comment by roysouma** [comment]
Hi rosolko,

I unhid the command prompt and saw it is firing up old chrome driver:

Starting ChromeDriver 78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}) on port 58584
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

DevTools listening on ws://127.0.0.1:58588/devtools/browser/6bd47f37-28ab-4a33-8763-ea592ed58d4b

**Comment by roysouma** [comment]
[packages.zip](https://github.com/rosolko/WebDriverManager.Net/files/4173856/packages.zip)

**Comment by roysouma** [comment]
Hi rosoljo,

I could debug the issue and find the root cause. The issue is occurring at line Environment.SetEnvironmentVariable(name, newPathVariable, EnvironmentVariableTarget.Process); in WebDriverManager. It is not throwing any error but also not adding to PATH. Hence it is not finding the correct webdriver.

So what do I have to do so that it add the chromedriver path properly in Environment variables?

**Comment by rosolko** [comment]
Check if your current path variable. 
Is it contains 78 chromedriver version path? 
Is it contains 80 chromedriver version path?

**Comment by roysouma** [comment]
It was some system issue. Uninstalled VS and deleted package. Reinstalled VS and checked out package and now everything went back to normal.
