### ISSUE TITLE
If we pass 'Latest' word to firefox , it is not able to download the driver. This is downloading sometimes, but most of the time it is failing

### ISSUE THREAD

**Issue by Anuja1408** [rosolko/WebDriverManager.Net#67]

**Comment by rosolko** [comment]
Can you please provide some information?
Currently you no need to provide any version if want to use latest one

**Comment by Anuja1408** [comment]
If we pass 'Latest' keyword in chrome, driver is downloading successfully.
new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig(), version: "Latest");

Same way , if we pass 'Latest' keyword in firefox, driver is not downloaded. But sometimes , it is downloaded . Drivers are not downloading consistently.
new WebDriverManager.DriverManager().SetUpDriver(new FirefoxConfig(), version: "Latest");

**Comment by rosolko** [comment]
Can you please also provide an error or logs if exists?

**Comment by Anuja1408** [comment]
system.io.filenotfoundexception is thrown if version is latest for firefox

**Comment by rosolko** [comment]
Unfortunately I'm unable to reproduce this issue and unable to fix it :(

**Comment by Anuja1408** [comment]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The system cannot find the file specified.WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging. 
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

This is the error I was getting. Please let me know you

**Comment by rosolko** [comment]
Look like the general problem is going from AngleSharp library, but I'm using this approach to get latest not only for firefox driver. Looks like need to deep analyze problem.

**Comment by Anuja1408** [comment]
Can you help us with any work around for this issue.

**Comment by rosolko** [comment]
Sorry, but I have no ideas how to work around this issue, even reproduce it :(

**Comment by kavyashreer23** [comment]
Hi Rosolko, 
Thanks for the quick response you are providing for the issues posted

The below links shows a issue with Angle Sharp 0.13.0. This is the same error we are facing. Could you please check and let us know your thoughts
https://github.com/AngleSharp/AngleSharp/issues/842

Thanks
