### ISSUE TITLE
WebdriverManager for firefox throws System.Net.WebException: Could not create SSL/TLS secure channel, in MS test agents and build deployed through jenkins

### ISSUE THREAD

**Issue by Anuja1408** [rosolko/WebDriverManager.Net#68]
When we tried to run our scripts on Test agents through Jenkins, we are encountering an issue with firefox and an issue as follows: 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. 

Tests are run in batch , with first test we see the above error and rest of the test scripts have two kinds of errors like above error and also System.NullReferenceException: Object reference not set to an instance of an object.

When we checked bin folder in test agent , firefox driver is not downloading. We ran the test scripts via command prompt, test scripts are running(firefoxdriver downloaded). 

Our code : 
new WebDriverManager.DriverManager().SetUpDriver(new FirefoxConfig(), version: driverVersion);
Driver = new FirefoxDriver(FirefoxDriverService.CreateDefaultService(), options, TimeSpan.FromSeconds(60)));

Note : When we run locally, we are not facing this issue.  

Appreciate your response ASAP. As we have implemented webdriverManager on large scale scripts on different products

**Comment by rosolko** [comment]
Looks like this is environment issue. Can say nothing about it, because know nothing about code, environment, full stack-trace.

**Comment by Anuja1408** [comment]
This is not happening for chrome , only for firefox we face this issue.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel
Stack Trace:
18:39:35     at System.Net.WebClient.DownloadFile(Uri address, String fileName)
18:39:35    at WebDriverManager.Services.Impl.BinaryService.DownloadZip(String url, String destination)
18:39:35    at WebDriverManager.Services.Impl.BinaryService.SetupBinary(String url, String zipDestination, String binDestination, String binaryName)
18:39:35    at WebDriverManager.DriverManager.SetUpDriver(String url, String binaryPath, String binaryName)
18:39:35    at WebDriverManager.DriverManager.SetUpDriver(IDriverConfig config, String version, Architecture architecture)

Can you please suggest us on this environment issue ?

**Comment by rosolko** [comment]
As I found [here](https://stackoverflow.com/a/2904963) for Windows XP, in Windows 7 solution required additional configuration

**Comment by kavyashreer23** [comment]
@rosolko This issue can be closed. Just before Firefox driver download call, we are forcing the application to use TLS1.2 security protocol
