### ISSUE TITLE
Manager downloads only latest version of the driver for Edge

### ISSUE THREAD

**Issue by gjarosz** [rosolko/WebDriverManager.Net#7]
I tried to run some tests on Windows 10 (I`m before upgrade), so the correct version of driver for my system is the one labeled "[Release 14393](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/)" on Microsoft's site

I tried to choose the right version using:
`new DriverManager().SetUpDriver(new EdgeConfig(), "3.14393");`

When I tried to run some tests using the driver a strange error about **msldso.dll** missing is shown (I googled that, it's related to **wrong version of the driver** being used. It seems that similar project but for Java has [similar issue ](https://github.com/bonigarcia/webdrivermanager/issues/106))

Driver is downloaded into **"Edge\3.14393\X64\"** folder. Right clicking on a downloaded file and going to the details tab reveals that file version is **10.0.15063.0**. so that's part of the newer driver from "**Release 15063**"

From what I've seen in **EdgeConfig.cs** versions and download urls are taken from the Microsoft site. We have all version numbers and download links but we're taking only **first (latest)** one.

Since Edge config doesn't use the "<version>" markers in urls, these are not altered by **UrlHelper** when manager tries to get the right download URL.

I was able to use desired version of the driver by configuring it manually:
```
new DriverManager().SetUpDriver(
                        "https://download.microsoft.com/download/3/2/D/32D3E464-F2EF-490F-841B-05D53C848D15/MicrosoftWebDriver.exe", 
                        Path.Combine(Directory.GetCurrentDirectory(), "Edge", "3.14393", "X64", "MicrosoftWebDriver.exe"),
                        "MicrosoftWebDriver.exe"
                        );
```

### So I`m kindly asking for a support for selecting Edge driver versions in an simpler way.

**Comment by rosolko** [comment]
@gjarosz You're correct. It's hard to automatically get right link for selected version because of Microsoft release strategy with strange download links.
In this case I decide to get only latest version by default. I don't want to hard-code download urls for some specific versions. 
And your solution with manual configuration good enough, because you're need some specific version.
I try to research this case and made some changes, but **PRs** are very welcome.
Stay turned.

**Comment by gjarosz** [comment]
Well. I was thinking how this can be changed to support other versions as well.
The good thing is that we are already pulling driver versions and urls when parsing microsoft's site, so instead of taking first item we could use whole list.

One idea I have was to introduce a method which would take into account version and architecture like:
`GetUrl(string version, Architecture architecture) {}`
And maybe change the GetUrl32 and GetUrl64 to accept version string as well.
This would make the UrlHelper and it's url rewriting logic no longer needed.

I'm aware that this change would need to be applied to interface and other drivers as well to make all things consistent. This change could break something, so it's worth considering all options.

Oh.. I forgot about some nice words to appreciate you work ;)
**Thanks for nice and clean package for managing webdriver's for selenium.**

**Comment by rosolko** [comment]
@gjarosz You're right this changes, I mean change build url strategy to create map and build, affect all code and implementations.
In this case I promote you to use your custom implementation of driver config, it easy and clear solution to use exact this version, and use standard implementation for latest version.
And you can also try to create your own implementation of _CustomConfig_ by implementing _IDriverConfig_ or even create custom implementation for _IVariableService_.
By the way I don't want to change all implementation only related to Microsoft strange release download urls.
**And thanks for your support words!**
