### ISSUE TITLE
Driver Download

### ISSUE THREAD

**Issue by clevsampaio** [rosolko/WebDriverManager.Net#71]
Hi, my question is to understand the purpose of your project is to download the chrome driver, edge and others if not, right?

But I'm trying to use it, but I'm trying this return when using EdgeDriver:

`OpenQA.Selenium.DriverServiceNotFoundException: The MicrosoftWebDriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://go.microsoft.com/fwlink/?LinkId=619687.`

Note: I have Edge installed on my machine.

**Comment by Piedone** [comment]
Same here. However, you can configure the path to the driver yourself when creating it:

```
                    var config = new EdgeConfig();
                    var architecture = ArchitectureHelper.GetArchitecture();
                    var version = config.GetLatestVersion();
                    var url = UrlHelper.BuildUrl(architecture == Architecture.X32 ? config.GetUrl32() : config.GetUrl64(), version);
                    var path = FileHelper.GetBinDestination(config.GetName(), version, architecture, config.GetBinaryName());

                    return new EdgeDriver(
                        EdgeDriverService.CreateDefaultService(Path.GetDirectoryName(path), Path.GetFileName(path)),
                        new EdgeOptions().SetCommonOptions()).SetCommonTimeouts(pageLoadTimeout);
```

So pretty much doing what `SetUpDriver()` does. Note that I've omitted a few things like it uses the latest version every time.

**Comment by clevsampaio** [comment]
First of all thank you very much for answering, about your answer and testest and still giving an error, this time you returned an error to me: OpenQA.Selenium.DriverServiceNotFoundException: The file C: \ Users \ - \ AppData \ Local \ Temp \ Edge \ 85.0.529.0 \ X64 \ msedgedriver.exe does not exist. The driver can be downloaded at http://go.microsoft.com/fwlink/?LinkId=619687

**Comment by Piedone** [comment]
Hmm, it seems that for you somehow it resolves the path to another folder. Anyway, try to figure out where WebDriverManager downloads the driver and configure the path to it in the ctor of EdgeDriver.
