### ISSUE TITLE
Check browser version too

### ISSUE THREAD

**Issue by Piedone** [rosolko/WebDriverManager.Net#73]
The [Java WebDriverManager ](https://github.com/bonigarcia/webdrivermanager) also checks the version of the installed browser, I'd guess to use a compatible driver, even if it's not the latest. It seems to me that this library doesn't do that, so it would be great if you could add this feature too.

Thank you for considering my suggestion.

**Comment by Piedone** [comment]
We at [Lombiq](https://lombiq.com) would like to sponsor this feature. Our primary concern is about running Chrome under Windows, should that matter. Would anybody like to talk about this? @rosolko?

**Comment by rosolko** [comment]
Unfortunately as for now I'm quite busy and don't have a time for work on it :(

**Comment by tteguayco** [comment]
This feature has been implemented for Google Chrome.

PR: https://github.com/rosolko/WebDriverManager.Net/pull/91

**Comment by Piedone** [comment]
So I think this should be closed too, right?

Also, @tteguayco @rosolko please get in touch with me via the e-mail address under my profile about the sponsorship I mentioned above.

**Comment by rosolko** [comment]
@Piedone Yes, also I want to merge #88 or #94 before release. I hope the new version will be released soon.

**Comment by Piedone** [comment]
Fantastic!
