### ISSUE TITLE
Download chromedriver 

### ISSUE THREAD

**Issue by orlagalvez** [rosolko/WebDriverManager.Net#79]
I'm having an issue when I try to start the app in a server it throws this error: "Access to the path 'C:\Windows\system32\Chrome\84.0.4147.30\X64' is denied" however we gave permissions to the user in that path and it still throwing the same error.

**Comment by rosolko** [comment]
Run IDE with admin privileged. You're running tests on system disk and for writing IDE should have a admin privileges.
