### ISSUE TITLE
Driver binaries are not downloaded

### ISSUE THREAD

**Issue by frankvu191** [rosolko/WebDriverManager.Net#8]
Hello,
I tried to use ChromeDriver but seems like the binary is not downloaded. Please see attachment for detail 
![2017-08-29_1354](https://user-images.githubusercontent.com/6407084/29808441-f130cf7e-8c4c-11e7-8494-19ac089d2a4a.png)
Thanks, 
Frank

**Comment by rosolko** [comment]
@frankvu191 That's strange. Tests on CI aren't failed.
Can you please specify, where do you store your tests?
Do you run you IDE with admin privileges?
Later I've try to reproduce this issue locally.
Thanks.

**Comment by rosolko** [comment]
@frankvu191 Sorry, but I can't reproduce this issue locally.
Library download archive to temporary directory. After that in unpack binary to project path like that: `<ProjectDirectory>/bin/Debug/Chrome/2.31/X32/chromedriver.exe`
Code that I've use:
```dotnet
using System;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;
using WebDriverManager.Helpers;
using Xunit;

namespace IntegrationTests.BrowserTests
{
    public class ChromeTests : IDisposable
    {
        private IWebDriver _webDriver;

        public ChromeTests()
        {
            new DriverManager().SetUpDriver(new ChromeConfig(), "Latest", Architecture.X32);
        }

        [Fact]
        public void ChromeTest()
        {
            _webDriver = new ChromeDriver();
            _webDriver.Navigate().GoToUrl("https://www.google.com/ncr");
            Assert.Equal(_webDriver.Title, "Google");
        }

        public void Dispose()
        {
            _webDriver.Quit();
        }
    }
}
```

**Comment by frankvu191** [comment]
Hi Rosolko,
Thanks for quick reply. I run the test with VS2017 on Windows 10 with param and without param to setup driver. I run with admin account in 2 different machines.
Kind regards,
Frank

**Comment by rosolko** [comment]
@frankvu191 Thanks for information.
Frank that was misunderstood I mean admin **privileges** for VS not admin **account**.
It looks like VS set current directory to VS location folder, and it's placed on `C` drive where you don't have direct access.

**Comment by rosolko** [comment]
@frankvu191 Any news or updates?

**Comment by frankvu191** [comment]
Sorry for late update. You are right, should run VS with admin privilege. It is working fine now.
Thanks
