### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 85

### ISSUE THREAD

**Issue by BilalKhan199** [rosolko/WebDriverManager.Net#81]
We are getting this error "session not created: This version of ChromeDriver only supports Chrome version 85" since yesterday.0
Current stable Version of chrome is 84 and 85 is still beta.

Workaround, disabled the driver manager and directly provided executable path works.
Any suggestion how to fix it?

**Comment by BilalKhan199** [comment]
Never mind this workaround worked

  new DriverManager().SetUpDriver(
                        "https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_win32.zip",
                        Path.Combine(Directory.GetCurrentDirectory(), "chromedriver.exe"),
                        "chromedriver.exe"
                    );

**Comment by Piedone** [comment]
Duplicate of https://github.com/rosolko/WebDriverManager.Net/issues/80. Good workaround!

**Comment by Piedone** [comment]
https://github.com/rosolko/WebDriverManager.Net/issues/73 would solve such issues too.
