### ISSUE TITLE
FirefoxConfig() returns "The remote server returned an error: (404) Not Found."

### ISSUE THREAD

**Issue by Dimitvp** [rosolko/WebDriverManager.Net#82]
I am not doing anything fancy. My implementation is straightforward:
`var driverManager = new DriverManager();

            if (isMozillaEnabled)
            {
                driverManager.SetUpDriver(new FirefoxConfig());

                FirefoxOptions firefoxOptions = GetFirefoxOptions();
                return new FirefoxDriver(firefoxOptions);
            }`
At driverManager.SetUpDriver(new FirefoxConfig()); I am getting the: "The remote server returned an error: (404) Not Found."

May be the problem is with me because at one point it was working correctly.

After trying all sorts of thing and nothing helped I debugged the WebDriverManager project and I noticed that GetLatestVersion() returns **.27.0** instead of **0.27.0**.
And because of that the URL is:
https://github.com/mozilla/geckodriver/releases/download/v.27.0/geckodriver-v.27.0-win64.zip
instead
https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win64.zip

If I did something wrong sorry for the Issue and please tell me what I have to do to fix it, but it seems to me that is not the case.

**Comment by rosolko** [comment]
@Dimitvp Yes, correct. The problem on library side. Mozzilla change version tag structure for a new version and it broke version parse. I'll take a look as soon as I can.

**Comment by rosolko** [comment]
Released in 2.9.3 version
