### ISSUE TITLE
Issue with geckdriver download due to url change

### ISSUE THREAD

**Issue by roysouma** [rosolko/WebDriverManager.Net#87]
Script is failing at new DriverManager().SetUpDriver(new FirefoxConfig());
On debugging i noticed that geckodriver download url now reads as https://github.com/mozilla/geckodriver/releases/tag/v0.27.0 instead of https://github.com/mozilla/geckodriver/releases/download/v0.27.0 (this is hardcoded in the FirefoxConfig). Hence 404 not found exception is being thrown.

**Comment by rosolko** [comment]
Hi, @roysouma. Unfortunately I can't reproduce this issue. If look at `FirefoxConfig` there is no changes in download url pattern for a long time.

**Comment by roysouma** [comment]
Hi, @rosolko , then what could be the root cause? it was working previously. Can you mention the url formed for latest gecodriver here which you are able to access manually also? I will try hitting the same url manually and then maybe I can dig deeper.

**Comment by rosolko** [comment]
https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win64.zip

**Comment by roysouma** [comment]
I was on 2.9.1 and the error persisted, but as soon as it updated to 2.9.3 it was resolved.
