### ISSUE TITLE
Unable to Open Config file:"End of Central Directory record could not be found"

### ISSUE THREAD

**Issue by AnisulKarim** [rosolko/WebDriverManager.Net#9]
Getting following error while trying to utilize Webdriver Manager 
new DriverManager().SetUpDriver(new ChromeConfig()), failed to open ChromeConfig() and got following error
"An exception of type 'System.IO.InvalidDataException' occurred in System.IO.Compression.FileSystem.dll but was not handled in user code"
Unzip software is WinRAR

Your help will be apprecaited
Thanks

**Comment by rosolko** [comment]
@AnisulKarim Fix published, looks like I've used wrong compression library dependency. Can you please try to update to 2.2.4 version and give feedback?

**Comment by AnisulKarim** [comment]
I updated to version 2.2.4, but still got the same error.Version 2.2.2 works perfectly fine in my colleague's work station but when i ran same test in my work station, it throw error 

**"An exception of type 'System.IO.InvalidDataException' occurred in 'System.IO.Compression.FileSystem.dll but was not handled in user code

Additional information: End of Central Directory record could not be found**


![capture](https://user-images.githubusercontent.com/19784540/33271478-5fe69508-d355-11e7-9de3-23cdced4c99f.PNG)

**Comment by rosolko** [comment]
@AnisulKarim Unfortunately I can't reproduce this issue and I didn't face that issue before. Can you please try to use some other unzip software such as 7zip?

**Comment by rosolko** [comment]
@AnisulKarim Any news?

**Comment by sid2934** [comment]
@rosolko My self and my colleague were experiencing this issue on 2/27/2019 we were able to fix this by deleting all files in the download location of the drivers. It appeared that the web driver that we were trying to use (Chrome) was corrupted or malformed. 

Figured that I owe it to you to grave dig this ticket. Thanks for the library its a great help.
