### ISSUE TITLE
new DriverManager().SetUpDriver(new EdgeConfig(), "Latest") receives System.Net.WebException: 'The remote server returned an error: (404) Not Found.'

### ISSUE THREAD

**Issue by DougShuffield** [rosolko/WebDriverManager.Net#96]
Working yesterday, but now getting 404 error when executing this line:

new DriverManager().SetUpDriver(new EdgeConfig(), "Latest");

Error:
System.Net.WebException: 'The remote server returned an error: (404) Not Found.'

**Comment by rosolko** [comment]
Looks like some time source Microsoft site not available
